// --> RELU INDEPTH 

// --> RELU --> GIVES SINGLE BEND
// --> PREVIOUS CLASS KA REVISION SEE IN NOTES PDF

// --> POINTS JO HAI NA X-10 AND X-30 AND ALL --> YE SAB WO KHUD SE KAREGA/HOGA APAN KUCH NI KARENGAI SELF --> A/C TO INPUT AND OUTPUT WE PROVIDE TO IT


// --> SEE NEW PATTERN --> RELU(X-10) + RELU(X-30) 
// --> AS INC HORA HAI --> 1 2 3 4 IN LAST PE SO + KARO NOT -
// --> **** WE CAN CHANGE DIRECTION OF NORMAL EQNS --> LINE(SLOPE) --> DEPEND ON QUESTION AND OUR THINKING PATTERN  


// -> RELU ON HIDDEN LAYER MEANS ?
//                _______
// ->   X ---->  |       |   --> RELU  
//                -------
// ->              WX + B
// -> O/P PE RELU KO LAGA RAY HAI SO HIDDEN LAYER PE BOLRAY HAI 


// --> SEE NEW PATTERN --> 3*RELU(X-2) - 3*RELU(X-3)
// --> OR BOHOT SARI EQNS BAN SHAKTI HAI 


// --> SEE NEW PATTERN --> 5*RELU(X-4) - 5*RELU(X-5)
// --> OR BOHOT SARI EQNS BAN SHAKTI HAI 


// ----> **** ACTIVATION FUNCTION AYE --> AP LINEAR EQN LIKHO MAI USME ATIVATION FUNCTION APPLY KARUNGA AND KISI BHI BAND KO CREATE KAR SHAKTA HU AND WO KISI BHI NON LINEAR EQN KO SOLVE KAR SHAKTA HAI 






// ------------ ALL THING DONE BY RELU -------------

// ----> Y = X^2 --> CURVE -> CREATE IT BY LINEAR EQN <- MODEL BANA DEGA CURVE KHUD DATA KO DEKH KE 
// --> SO SQUARE NIKALNA HAI TOH --> TAKE SUM OF 1ST 5 ODD NUMBERS
// --> 1 -> 1
// --> 2 -> 1 + 3
// --> 3 -> 1 + 3 + 5
// --> 4 -> 1 + 3 + 5 + 7 
// --> 5 -> 1 + 3 + 5 + 7 + 9

// --> **** ACTIVATION FUNCTION --> YE BHI DEKHTA HAI KI AT THE TIME KONSA NEURON ACTIVE HAI YA INACTIVE 
// --> IN A GRAPH --> 0 HAI SO INACTIVE NEURON THEN INC HUA SO ACTIVE HOGYA NEURON KOISA AND CONSTANT HAI LINE SO INACTIVE HOGYA NEURON KOI SA 

// SEE DIAGRAM IN NOTES --> 
// --> **** X = 2/....  SO SIRF 2/.... NEURON BS ACTIVE RAHE AND BAKI INACTIVE RAHE IS TYPE SE SAMJHE --> SO WE GET ANSWERS

// --> KOI SA BHI NEURON HAI SO WO O/P DEGA SELF VALUE,0 --> ACTIVE HAI TOH SELF VALUE DEGA OTHERWISE INACTIVE HAI TOH 0 DEGA O/P 
// --> ACTIVE --> SELF VALUE AS O/P
// --> INACTIVE --> 0

// -> SO ADD THESE ACTIVE NEURONS VALUE --> SO WE GET O/P OF THIS SQUARE WALA  

// -> SO JITNE KA SQUARE CHAIYE SO --> UTNE HI NEURON ACTIVE KARO AND BAKI SAB INACTIVE AND ADD ACTIVE NEURONS SO GET O/P 

// --> EQN FOR THIS :- EQN FOR PARTICULAR NEURON ACTIVE KAB HOGA 
// --> 5*RELU(X-2) - 5*RELU(X-3)  ----> FOR -----> X->Y, 1->0,2->0,3->5,4->5,5->5
// --> 3*RELU(X-1) - 3*RELU(X-2)  ----> FOR -----> X->Y, 1->0,2->3,3->3,4->3,5->3

// --> FINAL EQN [SUM OF FIRST N ODD NO'S] ----> RELU(X) - RELU(X-1) + 3*(RELU(X-1) - RELU(X-2)) + 5*(RELU(X-2) - RELU(X-3)) + 7*(RELU(X-3)-RELU(X-4)) + 9*(RELU(X-4)-RELU(X-5))+....
// --> CONCLUSION --> FOR 1 NEURON WE REQUIRE 2 EQN ATLEAST 
// OR
// --> FINAL EQN [SUM OF 1ST N-1 EVEN NO. + N ] --> RELU(X) + 2*RELU(X-1) + 2*RELU(X-2) + 2*RELU(X-3) + 2*RELU(X-4)


// --> **** ISSUE --> 100/1000/.. KA SQUARE FIND KARO ?
// --> SO REQUIRE 100/1000/.. NEURONS CHAIYE --> AND YE POSSIBLE HAI KYA KI APAN INFINITE NUMBERS OF NEURONS BANA SHAKE
// --> **** AYSA NI HAI --> MODEL KHUD HIDDEN PATTERNS FIND KARENGAI JISME LESS NUM OF NEURONS LAGENGAI <---- PREDICTIVE MODEL 
// --> **** AS JITNE JYADA NEURONS / JITNE JYADA PARAMS SO UTNI ACCHI ACCURACY ----> TIME JYADA LAGEGA THODA SA <---- PREDICTION 

// --> **** BOHOT SARI LINEAR EQNS THI USPE ACTIVATION FUNCTION LAGAKE APAN CRUVE EQNS MILEGI 



// --> **** KNOW KITNE NEURONS LAGENGAI ?
// --> BY PLOT GRAPH DEKHO BEND KITNE AARAY HAI -> AND JINTE BEND UTNE HI NEURONS CHAIYE HONGAI FOR A PERFECT CURVE 






// ----> Y = X^3

// --> PATTERN IS -> ADD 6,12,18,24.... IN LAST WALE PE AT EACH LEVEL 
// --> 1 | 1    --> 1
// --> 2 | 8    --> 1 + 7
// --> 3 | 27   --> 1 + 7 + 19
// --> 4 | 64   --> 1 + 7 + 19 + 37
// --> 5 | 125  --> 1 + 7 + 19 + 37 + 61
// --> 6 | 216  --> 1 + 7 + 19 + 37 + 61 + 91  
// --> 7 | 343  --> 1 + 7 + 19 + 37 + 61 + 91 + 127


// --> EQNS IS --> 1 * (RELU(X)-RELU(X-1)) + 2 * (RELU(X-1)-RELU(X-2))
// OR
// --> [RELU(X) + 6(RELU(X-1)) + 12(RELU(X-2)) + 18(RELU(X-3)) + 24(RELU(X-4)) + 30(RELU(X-5)] 


// ------> **** APPLY ACTIVATION FUNCTION IN LINEAR EQN GET ANY CURVE 


