// -------- **** 1) -> GRAPH-DB -------


// --> SUPPOSE KHUD KA LINKEDIN CREATE KARNA HAI :

// -> AND WE HAVE TO GIVE FRIEND SUGGESTIONS TO USERS -->  [2 LAKH USERS DATA]

// EXAMPLE -->

//    ///ROHIT///    <---CONNECTED---->   ///MOHIT/// 

// --> SO MAI KYA KARUNGA PEHLE DEKHUNGA KI ROHIT KIS FIELD KA HAI --> FIND KARO --> AND SUGGEST USKI FIELD KE USERS
// --> ROHIT JEE ASPIRANT HAI --> SO ROHIT KO JEE USERS + JEE FACULTIES + IIT STUDENTS SUGGEST KARO
// **** MAIN GOAL KI USER JYADA INVOVLE RAHE IN APPLICATION [USER ENGAGEMENT INCEREASE KARANA HAI APAN KO] --> SO PROFIT INCREASES


// ----------------------------------------------------------------------------------------------------------------------------------------------------------

// ANOTHER EXAMPLE FOR FUN : SUPPOSE FIRST TIME USER ENROLL IN YOUTUBE --> SO NOT HAVE ANY INFO RELATED TO THAT USER 
          
//     --> SO WHAT VIDEO WE SHOW TO THIS USER ?

//    --> FIRST THOUGHT :  [10 CRORE VIDEO YT DB] --> SO FIRST TIME NEW USER KO 50 VIDEO DIKHANAI HAI SO KONSI 50 VIDEO DIKHAO MAI USKO 
//             |
//             \/

//    --> SOLUTION1 : TOP 50 TRENDING YT KI SUGGEST KARDO ----> BEAST,TSERIES,VIRAL,ETC  ---> BUT KOI VILLAGE KA HAI SO BEAST KI ENGLISH VIDEO WASTE AND KOI AGED PERSON HAI TOH WO BHAJAN SUNEGA NOT RECOMMENDED SO ---> **** FAILS

//    --> SOLUTION2 : MIXED OF ALL CONTENT SHOW KARDO FIRST TIME --> SO JO WO SELECT KAREGA FIRST TIME TOH US HISAB SE AAGE KA CONTENT SHOW KARUNGA --> BUT ISSUE YAHA BHI HAI --> VARIOUS VARIETIES KE TOP 1-1 SUGGEST KARNA THA --> PER AGAR SONG PE ENGLISH SONG HAI KOI SA TREND PE AND SHOW AND USER DESI SONG SUNNA CHATA THA TOH --> WASTE ---> THIS WILL ALSO FAIL

//    --> SOLUTION3 : REGION[PLACE] PRIORITY DEKHO --> AP JAHA LIE KARTE HO US HISAB SE USER KO CONTENT DIKHAO --> WHEN 1ST TIME USER SIGNUP SO IP AND ALL SEND TO YT WO IP KE BASIC SE REGION/AGE MIL JAYEGA AND --> SUGGEST EASILY ACCORDING TO USERS PLACE AND AGE


// ----------------------------------------------------------------------------------------------------------------------------------------------------------


// ----------- LINKEDIN EXAMPLE -----------


// --> LET ROHIT --> 500 FRIEND 
//         VEDANT --> 500 FRIEND
//         ADIV --> 500 FRIEND
//        TULSI --> 500 FRIEND

// ----> Q1 **** FIND ROHIT KE FRIEND KE FRIEND KE FRIEND KON HAI GIVE LIST ?
// ----> Q2 TULSI MERE AYSE KONSE FRIENDS HAI JO GOOGLE PE WORK KARTE HAI FIND LIST ?
// ----> Q3 ADIV MERE AISE KONSE FRIEND KE FRIEND KON KON MICROSOFT PE HAI FIND LIST ?


// ------------------

// --> IN SQL DB : [FOR SEARCH IN SQLDB USES B+ TREE --> LOG(N) TIME ]


// TABLE ->  ////NAME////AGE////EMAIL////PHONE////FRIEND////COMPANY///


// -> Q1 ANSWER -> FIRST FIND ROHIT IN LOG(N) TIME --> THEN FIND FRIENDS OF ROHIT SO 0(1) TIME LAGEGA SO 500 FRIENDS MILE --> AGAIN FIND 500 FRIENDS OF FRIENDS --> SO 500LOG(N) TIME LAGEGA AND IT GIVES 2.5LAKH FRIENDS --> AB INKE BHI FRIEND KO FIND KARNA HAI SO TIME LAGEGA 2.5LAKHLOG(N)  AND LIST OF FRIENDS = 12.5CRORES   
            
//          -> TOTAL TIME COMPLEXITY = LOG(N) + 500*LOG(N) + 2.5LAKHLOG(N)

//          -> **** SO BOHOT JYADA TIME COMPLEXITY HAI FRIEND FIND KARNE KI IN SQL DB

//  ----> **** SO HERE BOTH SQL AND NOSQL DB FAILS [BOHOT JYADA TIME COMPLEXITY] + SQL MAI JOINS WAGERA LAGENGAI AND MULTIPLE TABLE HOGI SO OR COMPLEX HOJAYEGA --> SO FAILS FAILS FAILS BOTH SQL AND NOSQL TOO

// -------------------



// ------ GRAPHDB AYE [FOR RELATIONSHIP AND INTERCONNECTION]------


// --> SAME QUESTION1 ANSWER --> SEE IMAGE1 [KISI KA CONNECTION 1 WAY HOGA KISI KA 2 WAY HOGA]
 

//  ////ROHIT////  <---> ///MOHIT///
//         |   \             |
//         |    \            \/
//         \/    \        //ANJALI//
//  ///AMAN///    \                 /\
//                 \                 \
//                 \ /                \/
//              ///ROHAN// <--------> ////SOHAN

// --> HOW TO STORE THESE INFORMATION ? 
// --> **** THIS DIAGRAM IS LOOKS LIKE LINKEDLIST,GRAPH,ETC


// --> GRAPH BASED -->    
//                    NODES --> ROHIT,MOHIT,ANJALI,SOHAN,AMAN,ROHAN
//                    RELATIONSHIP --> ROHIT --> MOHIT, MOHIT --> ANJALI, ROHAN --> SOHAN, ETC       
//               -> **** ISME BOHOT LIKHNA PADEGA ALAG ALAG RELATIONSHIP ----> ******* BUT GRAPHDB'S LIKE NEO4J USES THIS APPROACH   
// 



//     -> (NOT USE THIS BY GRAPHDB)  LIST --> EASY + SHORT --> ROHIT : [MOHIT,AMAN,ROHAN] , 
//                                                             SOHAN : [ANJALI,ROHAN]     

//                   -> **** LIMITATION OF THIS LIST WALE KA [IMAGE2] --> DATA RAM/SECONDARY PE KAHA HOGA --> SO DATA IS IN SECONDARY MEMORY THIK [PERMANENT MEMORY WHERE AS RAM IS VOLATILE -> DATA LOST WHEN POWER OFF] 
//                                                            -> STORGAE PRESENT OF USERS PRESENT IN SECONDARY MEMORY THIK --> IMAGE2 --> TOH KYA 1 USER KA INFO BAR BAR STORE KARA HUA HAI A/C TO CONNECTION THIK HAI 
//                                                            -> **** MAAN LO NEW USER ATA HAI -> AND USER KE CONNECTION ALMOST SABKE SATH HAI ----> **** TOH PHIR HAR JAGAY ****UPDATE KARNA HOGA NA ISSUE AND SIZE INC HOGA TOO
//                                       
//                   ---> **** SO THIS SYSTEM FAILS OF LIST         




//  -> IMAGE3 --> LIST WALI APPRAOCH HI HAI BUT STORE ADDRESS IN RELATIONSHIP NOT ACTUAL DATA
//                     -> FIRST STORE INFO OF USER INDIVIDUALLY AND HAVIND ADDRESS TOO  ---> [NODES]
//                     -> **** SO STORE ADDRESS ONLY AND POINT KARAO ADDRESS KO ONLY --> NOT ACTUAL DATA STORE KARO --> SO STORGAE LESS LAGEGI





// ******** BUT IN REAL WORLD MAI ----> ADDRESS KO BHI STORE NI KARANA HAI ---> BUT WHY AND WHAT WE STORES ?

// -> **** BUT BINA ADDRESS KE TOH KISI PARTICULAR KO BHI FIND NI KAR SHKTE NA YR TOH ?

// -> LET DATABASE HAI --> BUT WHAT DATABASE KYA HAI -->  **** DB IS A COMPUTER/SERVER -> HAVING RAM,PROCESSOR,SSD,ALL

// -> IMAGE4 -> INSERT ALL ADDRESS WALA KAHANI IN THIS DB

// -> SUPPOSE KUCH HUA AND SYSTEM[DB] CRASH SO --> APNI INFORMATION GAYAB KYA AND COURSE ACCESS CHALA GAYA MERE KYA ? -----> NAHI NAHI NAHI

// -> **** REPLICAS CREATE HOTI HAI --> SINGLE DATA OF USER STORE IN MULTIPLE SYSTEMS AND ALL PRESENT IN DIFFERENT LOCATIONS --> IMAGE5

// -> COPY PASTE DATA FROM 1DB SE ANOTHER DB [IN REPLICAS] 

// --> ****** SO KYA GUARANTEE HAI KI USER KO ****SAME-MEMORY-ADDRESS-ALLOCATE HOGA IN --> DB/COMPUTER -> YE USKO[USER KO] APNE HISAB SE MEMORY ALLOCATE KARAYEGA NA [AND ** DIFFERENT MEMORY HI ALLOCATE HOGI USER KO IN DIFF COMPUTER/DB]


// ********** CONSLUSION --> 1 SYSTEM SE DUSHRE SYSTEM PE DATA COPY PASTE KARENGAI TOH ADDRESS CHANGE HOGA HI ---> SO WE ****DONT WRITE ADDRESS HARDCODE KARKE SAMJHE




// --> **** SOLUTION ARRAY KE AROUND HAI 


