// --> SEE PDF

// ----> LINEAR EQUATION KE BAARE PE PADHE APAN ABHI TK 
// --> SEE EQN AND GRAPH TOO
// --> FIND LINE EQUATION TO MAKE GRAPH 
// --> ABHI TK APAN SIRF LINEAR STRAIGHT LINE KI EQN BS SOLVE KAR PATE HAI THIK




// ----> HOW TO SOLVE QUADRATIC EQNS :-

// --> PLOT GRAPH -> BY QUADRATIC EUATIONS VALUES -> WE GET CURVE / CIRCLE AND ALL 
// --> CURVE LOOKS LIKE COMBINATION OF 2 STRAIGHT LINE --> BUT HOW TO COMBINE THEM --> WRITE IN NORMAL PROGRAMMING WE WRITE IT -> IF(X>3) RETURN 0 ; ELSE RETURN X-3;
// --> **** WE ALSO USE IF ELSE IN DEEP LEARNING --> BY FINDING PATTERNS IN DATA
// --> **** BUT WE STUDY DL WHEN WE CANT FIND PATTERN IN DATA --> KI PREDICT KARKE ANSWER NIKAL PAYE --> NOT FIND PATTERN IN DL --> SO CANT WRITE IF ELSE LOGIC CODE IN DL ****

// --> SO CURVE HAI USKO KAISE REPRESENT KARO GAI 
// --> **** SEE EQN IN PDF --> BY COMBINING BOTH LINEAR EQNS --> **** WE CANT GET THAT CURVE --> GET LINE EQNS ALWAYS
// --> **** KUCH BHI KARLO WE GET STRAIGHT LINE --> BY COMBINE MULTIPLE LINEAR EQNS

// ----> **** KHUD KE END PE LOGIC BUILD NI KAR SHAKE INTUTION BUILD NI KAR SHAKTE --> SO WE STUDY DL 
// --> JAHA PATTERN DIKHE SO NORMAL CODE LIKH DO IF ELSE OTHERWISE USE DL FOR FINDING PATTERNS 

// --> **** WHY NEED TO FIND PATTERN ? --> FOR EASY WAY WE FIND PATTERNS --> TABLE YAAD THODA NA HAI MEKO --> PER PATTERN FOLLOW KARKE LIKH LETA HU 





// ----> NEURONS AYE --> ACTIVATION FUNCTIONS AYE --> FOR SOLVING CURVE :-

// --> ACTIVATION FUNCTIONS -> RELU :- JO BHI O/P AARA HAI 0 SE CHOTA HAI SO 0 BANA DO AND +VE KO CHERNE KI KOSIS NI KARUNGA
//                          -> KAHI PE BHI ACTIVATION FUNCTION LAGA SHAKTE HAI --> SEE IN PDF 
//                          -> TO GET CURVE / BEND --> THAT SOLVE QUADRATIC AND CUBIC EQNS 

// --> W0 + B --> WHY WE WRITE THIS ?
// --> ISKO KISNE BANAYA AND WE CANT WRITE THIS EQNS --> W1X + W2X^2 + W3X^3 + ....  
// --> **** B/C --> HM ISKO KAHA TK LIKHE GAI BATAO BADE BADE RELATION HO SHAKTE HAI NA --> SO WE CANT PATA LAGA SHAKTE HAI KI KAHA TK EQNS LIKHNA HAI --> WE KNOW KITNE INPUT HAI BUT NOT CONTROL THE RELATIONSHIP SO AYSE NI LIKH SHAKTE HAI KI KONSI POWER RELATION HAI
// --> SO WE WRITE NORMAL EQN KE TERM PE --> W0 + B

// --> **** SO BY RELU WE GET BEND --> AND KI LESS THAN AND 0 HAI SO 0 +VE PE +VE VALUES 

// --> ******** BASICALLY BY RELU A.F. WE APPLY IF-ELSE IN DEEP LEARNING --> AND GET 1 CRUVE / BEND 
// --> 1 SINGLE BEND RELU FUNCTION INTRODUCE


// --> **** SO AGAR BOHOT SARE NEURON KA USE KARENGAI TOH WE MAKE MULTIPLE CURVE WALA DIAGRAM 




// --> **** 0 THEN NORMAL GRAPH --> THEN GET 1 SATURATION KI PHIR USKE BAAD CONSTANT HO JATE HAI 
// --> APPLY 2 RELU ACTIVATION FUNCTION
// --> RELU(X-10)   -   RELU(X-30) --> SO GET 2 BEND CURVE   
//        |                   |
//        \/                  \/
//    -ve AND 0 KE LIYE 0     30 KE BAAD STRAIGHT CONSTANT HO JAYE   
//    +VE KE LIYE STRAIGHT 

// --> **** BICH PE STRAIGHT LINE AYEGI AND 2 CURVE MILENGAI B/C OF 2 RELU A.F. 
// --> RELU(X-10)   -   RELU(X-30)
// --> **** NO EFFECT UPTO 20 BUT 30 SE EFFECT ANA SURU HO JAYEGA BY EQN AND GET CONSTANT LINE 
// --> KI 30 KE BAAD JO INC HORA HAI USKO CONSTANT KARDO BY EQN --> RELU(X-10) - RELU(X-30)
