// -----> ATTACK <-----


// FORMULA/FUNCTION CREATE KAR SHAKTE HAI NORMAL CODING SE
// INPUT -> FUNCTION(x) -> OUTPUT


// ----> DEEP LEARNING CONCEPTS :-
// -> CODE NI LIKH SHAKTE HAI KUCH CHIZO KA EX: IMAGE PE KYA HAI BATAO ?
// -> SYSTEM SE BOLTE HAI APAN CREATE KAR YE LE INPUT AND OUTPUT DONO AND PATTERN BATA ->
// ->  INPUT ----> FUNCTION(x) ----> OUTPUT



// ->  INPUT ----> FUNCTION(x) ----> OUTPUT
// -> ANTROPHIC : KO NI PATA KI UNKA SYSTEM KIS DATA PE TRAIN HUA HAI -> AND KONSA FUNCTION CREATE KIYA HAI YE BHI NI PATA ----> THESE THINGS ARE PRIVATE SIRF ENTROPIC KO PATA HAI BS
//                -> DATA TRAIN  (NOISY DATA HOGA -> USKO ENTROPHIC PE FILTER KARA HOGA AND ALL -> TIME COST LAGA HOGA)
//                -> FUNCTION()
// -> KAR CHUKE HAI TRAIN AND ALL PER AB NI PATA ENTROPHIC KO DATA AND FUNCTION



// -> DEEPSEEK NE KYA KIYA -> ENTROPHIC KI API KEY LELI -> AND DEEPSEEK NE 10 MILLION SE JYADA INPUT CREATE KARE THIK AND 10 MILLION OUTPUT MILE ISKE --> SO DEEPSEEK KO PROPER DATA MIL GYA --> TO TRAIN DEEPSEEK MODEL 
//                         -> **** DEEPSEEK DATA COLLECT KARNE PE BACH GYA -> USNE TOH ENTROPHIC KI API USE KARKE DIRECT DATA NIKAL LIYA [**** TIME BACH GYA BHAI -> BHALE API PE PAISA LAGA -> BUT NORMAL NOISY DATA SE WO KARTE TOH BHI PAISA LAGTA NA SO KITNA SAHI THA YR DEEPSEEK NE DIMAG LAGAYA BOHOT]

//                 /////// 
// INPUT ---------> MODEL ----------> OUTPUT
//                 ///////

// **** SO YE DEEPSEEK KA MODEL TOH ENTROPHIC KE MODEL JAISE HOGYA NA

//                 /////// 
// INPUT ---------> MODEL ----------> [0.84,0.16] [**** PROBABILITY HOTI HAI KI YAHI INPUT KA OUTPUT HO SHAKTA HAI]
//                 ///////        EX: (DOG , CAT)       [JISKI PROBABILITY JYADA WO ANSWER]


// ----> ******** SO DEEPSEEK NE OUTPUT PE ****PROBABILITY MANGI ****NA KI PROPER OUTPUT --> SO PROBABILITY WALA PUCHA DEEPSEEK NE BHAI SAHAB DIMAG 
// ----> DEEPSEEK NE BHALE 10K ACCOUNT SE API KEY LI PAYMENT KARI AND YE SAB KARA [TOH ISKO CHORI NI BOLENGAI] --> AND JALDI SE APNE MODEL KO TRAIN KAR LIYA --> DEEPSEEK NE ENTROPHIC KI APIS KI MADAD SE
// ----> AND THIS IS A DIKKAT/ISSUE IN ENTROPHIC PE --> AND YE BOLRAY KI CHORI KIYA HAI DEEPSEEK AND ALL NE


// ----> **** SO AB KYA HORA HAI KI GEMINI , OPENAI , CLAUDE PE RESTRICTIONS LAGI HUI HAI KI --> INKE MODELS KI FULL CAPABILITY/INTELLIGENCE US ARMY KO DENI HONGI ----> SO CLAUDE KE CEO NE MANA KAR DIYA SO CEO OF CLAUDE KO DHAMKAYA GYA --> SO APIS KEY NI DERAY HAI CLAUDE,GEMINI,OPENAI --> YE SAB DIKKAT KE KARAN ----> TOH APIS KEY KHARIDNE PE DIKKAT AARI HAI SAMJHE ---> DUE TO HARD RULES AND REGULATIONS


// --------------------------------- THIS WHOLE PROCESS IS DISTILATION PROCESS ---------------------------



// --> US BEHIND THE SCENE KYA KARTA HAI --> KI HIGH CONFIGER CHIPS US KE ALAWA KAHI NI BECHI JAYEGI ----> BUT KAHI SE DEEPSEEK NE FRAUD SE LELI CHIPS --> B/C IN MODEL TRAINING HIGH CONFIGER CHIPS REQUIRE 




// -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



// ------- PROJECT LIKE CODEX -------


// -> BUILD IT BY GEMINI LIKE REAL INTERVIEWS NOWADAYS

// -> see ai-studio-chat ----> AI Website Builder: System Architecture
