// -------> BINARY CLASSIFICATION <-------


// --------- EXAMPLE (PREDICTION) ---------

// --> PLACEMENT LAGEGI KI NI ?
// --> DEPENDS ON VARIOUS FACTORS :- AND WE DO BINARY CLASSIFICATION AT LAST 0/1 YES/NO 


//    X                  Y                  Z                 K
//   DSA (W1) |    ATTENDANCE (W2) |    PROJECT (W3) |   APTITUDE  (W4)   |   OUTPUT
//   
//    70               78                   3               70                  0   
//    80               76                   4               80                  1
//    ....
//    1 LAKH DATA


// --> **** HOW TO GET W1,W2,W3,W4 VALUE AND THRESHOLD VALUE ?
// --> USE NEURAL NETWORK SO USE THIS FORMULA 

// --> OUTPUT --> [W1*X + W2*Y + W3*Z + W4*K + B]

// --> LET THRESHOLD HAI 270 --> SO ISE JYADA JISKA SCORE HOGA USKA PLACMENT HO JAYEGA 1 AND LESS HAI TOH NI HOGA PLACEMENT 0 
// --> A SCORE = 800 , B SCORE = 900 , C SCORE = 200 , D SCORE = 400  ----> SO B KE HIGH CHANCES HAI TO GET PLACED 

// --> FIRST TAKE RANDOM VALUES -> W1,W2,W3,W4 --------->
// --> O/P MILEGA [B/W 0 AND 1] BUT WE GET 80 AS O/P ---------> SO WE HAVE TO MAKE IT INTO 0-1 BY OUR DIMAG --> SO 80 SCORE HAI TOH ISKO APAN 0.7 BOL SHAKTE HAI AND 70% CHANCES HAI KI PLACMENTS HO SHAKTI HAI
// --> SO SABSE BEST KYA KARO 0.5 SE UPER HAI SO PLACCMENT YES 1 OTHERWISE NO 0

// ----> 0 <= SCORE <=1 ----> AYE THIK THEN WE PREDICT YES/NO OR 0/1 

// --> **** APAN PREDICT TOH KARDIYE BUT PROBABILITY BHI BATAO 



// ----> **** HOW TO GET KI AGAR SCORE 80 HAI TOH 0.7 AND 70% CHANCE HAI KAISE AYA BATAO ?
// --> **** GPT BY ROHIT BHAIYA --> BY SIGMOID FUNCTION --> WE GET O/P IN B/W --> 0 TO 1 <-- BOHOT SARE FUNCTIONS HAI BUT SIGMOID IS BEST ONE 



// --> W1=3,W2=4,W3=0.2,W4=-5,B=10 -----> SO 80 WE GET --> CONVERT IT INTO B/W 0 TO 1 SO GET ----> 0.7 ----> SO FINAL 1 O/P WE GET 

// --> LOSS FUNCTION / ERROR  == 1 - 0.7 == 0.3
// --> W1 == W1_OLD + 0.01 (LEARNING RATE) * 0.3 (ERROR)  * 70
// --> SAME FOR W2,W3 AND ALL  



// --> LET O/P = 90 -----> GUESS IS 0.8 -----> O/P IS 0
// ERROR = 0-0.8 == -0.8
// W1 = W1_OLD + 0.01 * -0.8 * INPUT   <------- NORMAL JINDAGI




// ----> MENTOS JINDAGI (THINKING DEVELOP)

// --> FOCUS ON SIGMOID GRAPH
// --> 1 POINT KE BAAD GRAPH SATURATE HO JATA HAI --> X VALUE IS B/W O-1 --> WE NEED CORRECTION THIK 
// --> SO CURRENT METHODS WE USE IS CORRECT OR NOT 

// X = 10 LAKH --> 0.99995....        (BOTH ARE ALMOST EQUAL)
// X = 10 K ---> 0.999914.... 

// --> INME CORRECTION APPROX SAME HOGA BUT VALUE DIFF BOHOT HAI 10LAKH ANA 10K  
// --> ERRORS = 0.0001

// --> OUTPUT --> 0.8 
//                       <-------   1  
// --> OUTPUT --> 0.3  
//             CORRECTION


// --> **** AND UPER DEKHO DONO KE O/P ALMOST SAME HAI ----> SATURATION KI TARAF JARI HAI --> AFTER SOME TIME CONSTANT 
// --> CORRECTION BHI SAME HAI --> BUT REAL VALUE PE BOHOT DIFF HAI --> AND PUNISH KAISE KARE BATAO  
// --> SO CURRENT METHOD PUNISH KARRA HAI KYA ABHI --> NAHI


// -------------- CURRENY METHOD FAIL SA LAGRA HAI -------------
// --> **** SO KOI SA **** NEW ERROR FUNCTION INTODUCE KARO KI PUNISH KARE SAHI SE --> SO WE GET CORRECT O/P --> WHICH ARE GETTING WRONG BY SIGMOID 
// --> SO W1,W2 WAGERA KO CHANGE KANE KE LIYE NEW ONE INTRODUCE KARO KI SAHI SE PUNISH KARE AND WE GET CORRECT O/P  

