// --> MULTICLASS CLASSIFICATION 

// --> SEE PDF --> WE HAVE MULTIPLE OPTION IN O/P SO SELECT CORRECT ONE IS --> MULTICLASS CLASSIFICATION 


// DSA  |    PROJECT   |   IQ     |  ATTENDANCE     |   CGPA    |  OUTPUT
// 200         4           110           80               8.4        1
// ....

// --> BOHOT SARI COMPANIES HAI TOH HAR COMPANY PE SELECT HONE KI KUCH NA KUCH PROBABILTY HOGI KI SELECT HO SHAKTE HAI BASED ON THEIR I/P DATA
// --> AND SUM OF CHANCES TO GET PLACED IN ALL COMPANIES IS ALWAYS = 1
// --> IN ALL COMPANIES 1 IS WINNER JISPE WO PLACE HOGA 


// WAY1 :- 
// --> INDIVIDUAL LEVEL PE DEKHO KI MICROSFT , GOOGLE AND ALL PE HOGA KI NI 
// --> 90%  --> MICRSOFT
// --> 70%  --> GOOGLE
// --> 74%  --> TCS
// --> 85%  --> UBER
// ..... 10 COMPANIES

// -----> **** SO SIRF 1 KO BS SELECT KARNA HAI -> SO WE SELECT MICROSOFT B/C ISME JYADA CHANCE HAI SELECT HONE KE 
// --> SO CREATE MODELS FOR EACH COMPANY SO WO BATAYEGA KI --> SELECT HUE KI NI IN THAT PARTICULAR COMPANY --> YES BY 1 NO BY 0 
// --> **** SO APAN NE 10 MODELS BANAYE AND 10 MODELS TRAIN KARE --> SO AB PATA LAGEGA KI KISME HIGH CHANCES HAI SELECT HONE KE 

// ----> SO YE EK BINARY CLASSIFICATION KA EXAMPLE HAI AB ----> ISSUE KYA HAI YAHA PE ----> COSTING BOHOT SARE MODELS CREATION AND TESTING 


// **** ----> SOLUTION --> EK SATH SAB WORK HO ALAG ALAG NA HO --> THAT IS MULTICLASS CLASSIFICATION 
// --> [0.2 , 0.3 , 0.1 , 0.15 , 0.16 , ....]  ---> YE MULTICLASS CLASSIFICATION BATEAGA BUT THIS IS NOT PROBABLITY KI ITNA CHANCES HAI TO SELECT IN COMPANY --> YE BEST ONE BS BATAYEGA 
// --> SO ISME AYSE AYEGA --> [30% IN MICROSOFT , 15% IN GOOGLE , AND ALL]  --> TOTAL IS 100% 
// --> SO BEST CHANCE HAI IN MICROSOFT

// --> **** WE GET O/P PE --> 1 2 3 4 .... <- AS NEURAL NUMBER PREDICT NUMBERS 
// --> 1 -> AMAZON , 2 -> GOOGLE , ........    [LABELLING] 

// --> W1X + W2Y + W3Z + W4K + W5M + B = OUTPUT
// --> **** APAN O/P KO KISPE DEKHE --> 1,2,3,4   <--------- RADDI METHOD --> B/C IF TRAINING DATA IS INCORRECT / KACHRA SO WHAT OUR MODEL WILL PREDICT --> KACHRA ANSWER MILEGA NA 
// --> 1 -> AMAZON , 2 -> GOOGLE , ........ THEIR IS NO MEANING/RELATIONSHIP OF THIS DATA IN O/P B/C YE HAMARE HISAB SE HAI VALUE ASSIGN SO AYSE O/P NI WO KARA SHAKTE **** YE SIEF LABEL HAI THIK OK FINE --> TOH HMNE KHUD GALAT KAR DIYA DATA SO WRONG PREDICT HI KAREGA NA
// --> THIS IS CORRECT ---> KI --> 0.2 , 0.1 AND ALL [IN 0 TO 1 RANGE]

// --> SEE DIAGRAM :- PREDICT SCORE IN LAST LAYER --> 10 O/P A/C TO COMPANYS [GET 10 RAW SCORE ---> 1-> MICROSOFT,2->GOOGLE,....]  

// --> PREDICT 10 O/P NUMBERS --> [__,__,__,__,__,__,__,__,__,__] --> [__+__+__+__+__+__+__+__+__+__] = 1
// --> **** CONVERT THESE RAW SCORES INTO 0TO1 RANGE AND PROBABLITY = 1 HO --> SO WE PREDICT CORRECT O/P JISKI BHI PROB JYADA HO 

// --> __ / TOTAL --> WALA METHOD IS WRONG SOMETIMES FOR -VE NUMBERS SO THIS FAILS --> 

// --> ANOTHER WAY --> UPER WALE PE -VE KA ISSUE THA TOH --> NORMALIZE KARKE +VE BANA LO SABKO --> THEN APPLY SAME METHOD IN IT -----> THIS IS BEKAR METHOD TOO B/C YE NA VALUES KE BICH KE DIFFERENCE KO GAYAB KAR DETA HAI  
// --> SEE EXAMPLE --> [-100000 , 10 , 1000]  ----> [0 , 100010 , 101000]   <---- GAP AGYA VALUES KE BICH PE BOHOT JYADA AND ORIGINAL GAP GAYAB --> PROB[0,4.9,0.51] BUT PROBABLITY PASS AYI PHIR BHI -> LAGRA KOI RELATION HI NI HAI 
// --> SO KUCH AYSA KARNA HAI KI -VE OR CHOTA HOTA JAYE AND +VE INC HOTE JAYE AND O/P 0TO1 KE BICH AYE AND GAP REHNA CHAIYE BICH PE AND SUM OF PROBBAILTY IS 1 AYE 


// --> ******** SO USE SOFTMAX FUNCTION --> e^100/sum*e^2 --> TO DO THIS RAW SCORES INTO 0TO1 RANGE AND PROBABLITY = 1 HO
// --> ******** -VE KO OR CHOTA BANAYE AND +VE KO INC KARE AND RELATIVE GAP NORMAL RAHE DIKHE AND 0TO1 KE BICH PE AYE VALUES AND 1 PROBABILTY AYE WHEN SUM KARE TOH 


// --> PAGENO-7 ******** JAISE AMAZON = 0.4 WALA HIGHEST HAI --> SO ISKO 1 KI TARAF INC KARENGAI [B/C TOTAL SUM IS = 1] ERROR KO CORRECT KARENGAI SO BAKI KE AUTOMATICALLY DEC HO JAYENGAI --> AND WE GET O/P  
// --> SUPPOSE CORRECT ANSWER IS GOOGLE BUT AMAZON BATAYA --> SO WEIGHT UPDATE KARO AB THIK BY BACKPROPAGATION
// --> ABHI TK APAN 1 LABEL PE KARRAY HAI NOT IN MULTIPLE PABEL PE NI KARRAY HAI [NEURON PE]
// --> PAGENO-6 IN SINGLE LEBEL JO ERROR AYA SO USKE HISAB SE WE CAN MANAGE WEIGHT UPDATION EASILY 

// --> PAGENO-6 **** IN MULTI CLASS CLASSIFICATION --> BACKPROPAGATION SE WEIGHT CHANGE KARTE HAI 


// **** --> LLM HAI SO WO NEXT WORD PREDICT KARTA HAI --> SO WAHA PE O/P LAYER PE WORDS KI PROBABILTY LIKHNI PADTI HOGI KYA --> YES FOR EACH WORD PROBBAILTY DEKHTE HAI --> THIK HAI NEXT WORDS KE ANE KI PROBABLITY HOTI HAI THIK FOR EACH WORDS AND SELECT WORD BASED ON TEMPERATURE
// --> LIKE MULTICLASS CLASSIFICATION LAGRA HAI NA --> KI HAR WORD KI PROBABILTY DEKHTE HAI 




// ----------> BACKPROPAGATION <---------

// STUDY   |    MARKS
//   3            30
//   4            40
//   5            50



// --> IN 1 LABEL ->

//   X ------> //////   ------> O/P 
//               W    
// -> O/P = W * X 

// ERROR = ACTUAL - PREDICTED
// SO ISKE BASIC PE WEIGHT UPDATE KARTE HAI

// W1_NEW = W1_OLD + N * ERROR * X                                                          (WE MULTIPLY IT HERE ERROR * X)    <-
// --> **** AS W1 PE KUCH ERROR RAHA HOGA THIK AND JAB WO X SE * HUA TOH BOHOT BADA BAN GYA OK --> THAT IS IN O/P <- BIG ERROR   | 


// --> IN 2 LABEL --> 
//  X  ------>   /////   ---Y--->  /////   ---Z---> 
//                 W1                W2 

// ERROR :-
// -> W2_NEW = W2_OLD + N * ERROR * Y 
// -> W1_NEW = W1_OLD + N * (ERROR*W2) * X   <- W2 ERROR SE * HOKE AMPLIFY KARRA HOGA ERROR 
//                            ERROR



// --> IN 3 LABEL --> 
//  X  ------>   /////   ---Y--->  /////   ---Z--->    /////   ------>  O/P 
//                 W1                W2                 W3

// ERROR :-
// -> W3_NEW = W3_OLD + N * ERROR * Z
// -> W2_NEW = W2_OLD + N * (ERROR*W3) * Y               <- ERROR INC HOTE JARA HAI 
// -> W1_NEW = W1_OLD + N * (ERROR*W3*W2) * X            <- ERROR INC HOTE JARA HAI


// **** -> JITNA ERROR PE CONTRIBUTION HORA HAI NA UTNI HI USKO PUNISHMENT MILEGI 
// **** -> ERROR INC HOTE JARA HAI -> JITNA FURTHER APAN MOVE KARRAY HAI THIK WEIGHT SE ERROR * HOKE --> ERROR INC HORA HAI THIK 



// --> THIS IS BACKPROPAGATION 


// --> SEE 1 MORE CASE IN PDF :- PAGE-11
// --> **** JITNA CONTRIBUTION IN ERROR UTNA JYADA PUNISH HOGA 



// --> ************ CHALLANGE :-

// -->        X ------>   ////////   -----> O/P
//                           W

// -> W1_NEW = W1_OLD + N * ERROR * X 
// --> WHY THIS X MULTIPLY HERE ? 
// --> WE SAY --> W1 = ( W_ACTUAL - W_ERROR ) * X  ---> EX:-  7 = 10 - 3  -> ACTUAL - ERROR KARRAY SO W1 KA VALUE AYA THIK
// --> X MULTIPLY HORA HAI --> SO --> W_ACTUAL * X = CORRECT O/P AND W_ERR * X = ERROR -> YE ERROR HAI EK THIK 
// --> SO JO BHI ERROR HAI USKE KARAN WRONG O/P MILRA HAI THIK --> ERROR = W_ERROR * X
// --> SO MUJHE W1 KE ANDER KUCH VALUE UPDATE KARNA HOGA THIK --> AND ERROR YE RAHA --> ERROR = W_ERROR * X --> APNE ERROR KO AMPLIFY KAR DIA HAI X SE * KARKE THIK 


// ----------> *********    W1 -----> W_ACTUAL + W_ERROR --> 2 PE BREAK HAI THIK NA  -->  EX:-  7 = 10 - 3




// -----> TAKE 2 INPUTS :-

//    X ------->       /////////
//                     /////////    ---------> O/P 
//    Y ------->       /////////

// -> O/P = W1*X + W2*Y 
//        = (W1_ACTUAL + W1_ERROR)*X + (W2_ACTUAL + W2_ERROR)*Y
//        = (W1_ACTUAL*X + W2_ACTUAL*Y) + (W1_ERROR*X + W2_ERROR*Y)
//                       |                             |       
//                       \/                            \/
//                    CORRECT                         ERROR 


// ERROR  ------->   W1 
//   |----------->   W2 

// --> FINAL/TOTAL ERROR PE APAN KAISE BATAYENGAI KI [FINAL ERROR PE DONO KO BATNA HAI] ---> W1 KI KITNI GALTI AND W2 KI KITNI GALTI HAI BATAO SO GALTI KE HISAB SE PUNISH HONGAI NA DONO ? 

// --> **** BATAO NA *X KYU KARE IN FORMULA ? 

// --> SEE EXAMPLE IN LAST PAGE OF PDF --> APAN EXTRA KISI SE THODA NA * KARRAY HAI KI ERROR INC HO JISKA JITNA ERROR UTNA CONTIBUTE KARE BS ----> SO KYU * X KARRAY HAI IN FORMULA ---> SO ISSE TOH INC HOGA NA ERROR YR BATAO AB ? 


// ----> **** ERROR KO DISTRIBUTE/DIVIDE KARE IN BOTH BY --> ERROR / W1_ERROR + W2_ERROR   ---> SO FORMULA PE TOH TERM ERROR NI AYEGA BUT *X TOH AYEGA HI ---> KOI MTLAB NI IS SOLUTION KA ---> W1_NEW = W1_OLD + N * ERROR * X

// --> **** BATAO *X KYU KARE IN FORMULA ? --> WHY ERROR NOT DISTRIBUTE *X KYU HORA HAI BATAO ? 


