// ------------------> MINI CODEX <----------------

// ARCHITECTURE :

// KOI SI BHI WEBSITE BANANA HAI TOH KYA DIKKAT AYENGI -> BOHOT SARI



// -> PROBLEM : AI SE KARWANA HAI JO USER KARTA HAI WHILE CREATING A WEBSITE [JO PROBLEM AYEGI USKO JAISE HUMAN SOLVE KARTA HAI USKO AI SE SOLVE KARANA HAI]


// -> USER       [YE PURA LOOP PE RAHEGA]
//     /\
//     |   
//     \/    
// -> PRODUCT MANAGER AGENT  [REQ GATHERING]
//     /\
//     |   
//     \/  
// -> ARCHITECTURE PLANNER [BACKEND,FRONTED,DB,FOLDER,API's,AND ALL] -> EK SATH SAB NI CHALANA HAI THODA THODA KARWANA HAI -> YA PHIR DHIRE DHIRE KARO RESTRICT KARDO -> KI FRONTED REACT SE HI HOGA , BACKEND NODE SE , BUT DB CHOOSE BY USER -> YE KARWA DERAY THIK       
//     /\
//     |   
//     \/  
// -> ARCHITECTURE EXECUTER [SO YE ARCHITECTURE PLANNER WALE KO STEP BY STEP IMPLEMENT KAREGA EK SATH NI KAREGA]
//     /\
//     |   
//     \/ 
// -> CODE PLANNER [PLAN KAREGA KYA KYA CODE KARNA HAI-> MIDDLEWARE,MONGO,AUTH,ETC]
//     /\
//     |   
//     \/ 
// -> HANDLER AGENT OF LATEST LIBRARIES  ->  [LATEST UPDATES/VERSION DEKHEGA AND BATAYEGA]      <---------->    NEW VERSION LIBRARY CODE [APAN PURA DOCUMENTATION NI LAYENGAI SIRF UPDATED WALA PART HI LAYENGAI] -> **** DIKKAT YAHA BHI HAI EX: SUM(A,B) -> OUR I/P SUM(2,3) OLD FUNCTION -> UPDATE DOCU TOH AYA [BREAKDOWN CHANGES] NEW SUM(A,B,C) SO I/P SUM(2,3) AB YAHA HAMARA WORK NI KAREGA I/P AND NEW EK OR AYA SUB(A,B) I.E. (NEW CHANGES) --> SO IN BREAKDOWN CHANGES APAN KO ISKO SOLVE KARNA HOGA NOT HAVE ANY ISSUE IN NEW CHANGES
//     /\                                                                                                       **** NOT FOCUS ON NEW CHANGES/EXTRA CHANGES ONLY FOCUS ON JO BREAK KARRAY UNPE  
//     |   
//     \/ 
// -> CODE WRITER AGENT [YE STEP BY STEP CODE WRITE KAREGA] -> 1) UPTODATE :- KISI KA V6 NEW HAI BUT ISKO V5 PATA HAI SO CODE BREAK HO JAYEGA V5 SE --> SO YE[UPTODATE] CODE PLANNER KO BATA DEKI V6 USE KARNA HAI ------> OR YA PHIR 1 NEW NODE BANA DO UPER DEKHO
//     /\                                **** [KYA YE BREAKDOWN CHANGES DEKH KE SAMJH JAYEGA SAB KYA ? -> DOCUMENTAION DEKH KE SAB CHAL JAYEGA KYA BS ? -> NI WE HAVE TO GIVE ] ----> ******** GIVE BREAK DOWN CHANGES + REAL WORLD IMPLEMENTATION -->  ***** BHALE TOKENS THODA SA JYADA LAGENGAI CHALEGA BUT SYSTEM ACHE BANENGAI
//     |                                 **** [APAN COST BACHA CHUKE HAI THODA SA BY ONLY SEE BREAKDOWN CHANGES NOT SEE NEW CHANGES]
//     \/                                **** [ASK QUESTION TO INNTERVVIEWER KI ENTERPRICE KE LIYE BANANA HAI KI USER KE LIYE --> ENERPRICE KE LIYE HAI TOH NO CONPROMISE -> MAST BANANA HAI SAB CHIZ TOKEN NI BACHAO JAISE APAN NE NEW CHANGES PE BACHAYE APAN YE NI KARNA HAI FOR ENTERPRICE KE LIYE -> USER KE LIYE HAI TOH TOKEN BACHAO THIK]
// -> CHECK THE BUG IN CODE AGENT    [BUG CHECK KARNA KI KISI TASK KO EXECUTE KARRA HAI -> EX: DATA KO DB PE SAVE KARADO -> BUT CHECK KI USER AUTH USER HAI KI NI -> AND APAN AUTH KA CODE PEHLE LIKH CHUKE HAI -> SO USE THAT AUTH CODE (CALL FUNCTION AND PARAMS AND KAHA LIKHA HAI WO BS PATA HO -> CONTEXT BHEJO) NOT WRITE AGAIN SAME CODE -> SO AB NA IMPORT EXPORT KA SAMJH AYEGA KI AUTH WALE KO IS FILE PE IMPORT AND ALL KARNA HAI SAMJHE]
//     /\                            [BHAI SUPPOSE 50 FILE MEIN CODE LIKHA HAI TOH MAI CONTEXT PE S0 FILE BHJEU KA AND HAR FILE PE 100 LINE KA CODE HAI -> SO 50*100 = 5000 SO 5000 LINE KA CODE CONTEXT PE THODA NA BHEJE GAI ----> ALTERNATE APPROACH KI FILE STRUCTURE AND FOLDER STRUCTURE DEDO + 1 DB(PINECONE/SQL) WAHA CODE STORE KARA DENGAI AND JO WALA CODE CHAIYE WO DB SE LELO AND FUNCTION NAME ARGS BS NIKALO AND CONTEXT PE DEDO BOHOT SARE TOKEN BACH GAYE BEST WAY]                      
//     |                             [PINECONE/SQL DB KOI SA BHI SAHI HAI KYUKI 50 FILE HAI -> ISME SE APAN KO CONTENT/CODE CHAIYE HAI SO KISI KO BHI USE KARLO]
//     \/                                   
// -> TESTING            [ACTUAL PE SERVER , FRONTEND HONA CHAIYE -> SO APAN TESTING KAR SHAKE -> APIS WORK KARNI CHAIYE -> GET PUT ETC -> HOW TO EXECUTE TESTING PHRASE ? --> AUTOMATION PE LEKE JANA HAI TOOLS CREATE KARNA HOGA -> FRONTEND,BAACKEND,DB KE CODE KO KAHI RAKHA JAYE AND CODE KO RUN KIYA JAYEGA AND SEE SAHI SE CHAL RA HAI KI NI]     
//     /\                [PEHLE EK SAFE ENVIRONEMT CREATE KARNA HOGA I.E. -> CREATE SANDBOX -> KI SYSTEM KA EK ISOLATED PART (ACCESS OF RAM,HDD AND ALL KA THODA SA ACCESS KI RUN AND TEST KAR SHAKE --> DO IT BY DOCKER IN VERY LESS MEMORY/RESOURCE)]
//      |                [ISOLATION WALA IS LIYE KARRAY HAI KI LLM KO SARE SYSTEM KA ACCESS NA MILE -> KUCH BHI CMD SE KUCH IMP UDA DIYA TOH -> SO ISI LIYE ISOLATED WALA CHIZE KI SIRF US PROJECT KE SATH KARE WITH THODE SE SYSTEM ENVIRONMENT SE SAMJHE]
//     \/                [JISKE PASS SE ERROR AYE USKO BATA DO KI ERROR AYA HAI RESOLVE KARKE DO]
// -> END


// -> **** [HANDLER AGENT AND CODE WRITER AGENT KE BICH] yaha pe baar baar uper niche call hoga small small tasks ke liye -> and new version check hoga ki mere pass ye hai apke pass new hai toh batao bar bar wahi wahi -> dikkat hai yr 
// -> solution ye ho shakta hai ki -> **** state pe store kara do kuch answer aya toh bar bar internet pe search na karna pade -> ki search hua toh state se answer du na ki internet se puche

