// ------------ GRAPHRAG PROJECT --> MOVIE QUERIES SYSTEM -------------


// --> PROBLEM STATEMENT : 1000 QUERIES DATA --> MOVIE NAME,DIRECTOR,ARTISTS,AWARDS --> PERFORM ANY QUERY IN 1000 MOVIES 
// --> RECOMMENDATION + ASK ANY QUESTIONS --> ACTOR-A NE KON KON SI MOVIE KARI HAI ACTOR-C KO KONSA AWARD MILA HAI AND ALL  


// SOLUTION --> FACTUAL INFORMATION (RELATIONSHIP) : GRAPH DB
//          --> SIMILARITY : VECTOR DB


// --> BUILD GRAPHDB FOR --> QUESTIONS LIKE --> KON KON ACTOR THAY IN INCEPTION MOVIE , WHO IS DIRECTOR OF INCEPTION MOVIE ?
//                       --> SO GRAPH SE RELATION SHOW KARATE HAI --> SEE IMAGE1 

//                       --> MEANING FULL GRAPH BANANA HAI NODES,EDGES[RELATIONSHIP] --> RELATIONSHIP SAHI SE BANANA HAI

//                       --> NODE KON KON SE HANGAI ? [STORES ACTUAL INFORMATION] 
//                           -> MOVIE , DIRECTOR , ACTOR , AWARD , GENRE , THEME 


//                       --> RELATIONSIP FIND KARNA IS IMP ? [RELATIONSHIP IS B/W NODES] [KITNE EDGES BANENGI -> RELATIONSHIP]
//                       --> SEE IMAGE2 --> APNE UPER HAI KITNE BHI RELATIOSHIP  BANA SHAKTE HAI APAN
//                       --> SEE IMAGE3 --> SHOW RELATIOSHIP VIA GRAPH 



//      --> BUILD A GRAPH AND THINK --> IMAGE4

//                 -> NODE PE **LABEL HOTA HAI TOH APAN PEHCHAN SHAKTE HAI KYA HAI YE NODE BY LABEL -> ACTOR,DIRECTOR,ALL --> AND NODE KE ANDER SE VALUE DEKH SHAKTE HAI PHIR 
                 
//                 -> QUERY : LIST ALL THE MOVIE DIRECTED BY NOLEN ? --> **TYPE[LABEL] IS IMPORTANT KI HO SHAKTA HAI NOLEN KAHI ACTOR HO AND KAHI DIRECTOR --> SO HERE DIRECTOR RETURN KARNA HAI A/C TO LABEL -> [ACTOR,DIRECTOR] 

//                 -> QUERY : RECOMMEND 10 MOVIE SIMILAR TO INTERSTELLEN ? 
//                     
//                     --> APPROACH1 --> GONERE AND THEME SE 50 50 MOVIE AND SELECT BEST-SIMILAR 10 AND RECOMMEND --> NOT EFFECTIVE BECAUSE IN REAL WORLD LAKHO MOVIE HOTI HAI  
//                     --> **APPROACH2 --> VECTORDB CREATE KARE KYA --> 1000 MOVIE KA --> VECTORDB 1000-VECTOR BANAYEGA -> AND SIMILAR 10 MOVIE DEDEGA THIK ----> **** NOT EFFICIENT B/C DEKHO HAR MOVIE KA 1 VECTOR HOGA THIK --> PER BOHOT SARI CHIZE DEKHNA HOGA SIMILAR KE LIYE -> ACTOR,DIRECTOR,GENORE,THEME,ETC --> NOT WORK PROPERLY VECTORDB METHOD 
//                                     --> **** BUT AGAR VECTORDB SE HI BOHOT SARI CHIZO KE BASIC SE COMPARE KARAKE SIMILAR 50 LIYE AND LAST PE --> SCIENCE-FRICTION[GONORE] JO JO HAI UNSE 10 MOVIE SIMILAR LE SHAKTE HAI SO HERE ****GARPHDB USE[KI MOVIE SCIENCE-FRICTION HAI KI NI BY DRAW GRAPH] --> EFFECTIVE      
//                                    
//                                     --> ****  SIMILARITY CHAIYE THI SO ----> USE ****VECTORDB AND RELATIONSHIP DEKHNA HAI SO USE ****VECTORDB -> AND ****VECTORDB REDUCES SEARCH AREA
//                                     --> ******** PEHLE TOP 50 LAYE *SIMILAR[BY VECTOR DB] WALI THEN --> TOP 50 MAI SE *RELATED[BY GRAPHDB] TOP 10 SHOW KARDO


//                 -> QUERY : FINAL ALL ACTOR WHO WORKED WITH NOLAN IN OSCAR WINNING MOVIE AND SAME ACTOR WON OSCAR AWARD IN DIFFERENT AWARD AND GENERE ?
//                     --> SOLUTION : NOLAN KI MOVIE FIND KARO JO OSCAR WINNING HAI --> AND UN MOVIES KE ACTOR FIND KARO WITH NOLEN --> THEN ACTOR NE KONSI DIFFEENRT MOVIE AND GENERE KARI JISME OSCAR JITA HAI 

//                     --> **** GRAPHDB PE DIRECT QUESTION[TEXT] NI SAMAJTE HAI --> USE ****QUERY LANGUAGE IN GRAPHDB FOR QUERY PERFORMING

//                      --> IMAGE5 --> **** KO DEKHO KI USER NE QUERY KI SERVER TAK GAYI QUERY AND VECTORDB SAMJH JAYEGA QUERY APNI BUT GRAPHDB NI SAMJHTA TOH FIRST SEND QUERY+NODEINFO+REALTIONSIP TO LLM THEN LLM GIVE QUERY SEND IT TO GRAPHDB --> SO GRAPHDB NE ANSWER RETURN KARA AGAIN GIVE IT TO LLM OR ACHE SE REFINE KAR DEGA ANSWER KO AND RETURN RESULT 
//                                 --> **** ONLY 1 PROBLEM LLM HALOSINATION --> LLM KUCH BHI QUERY DIYA AND DB HI DELETE KAR DIYA TOH --> YE ISSUE BS HAI ----> SOLUTION 2 LLM USE KARO 1 QUERY DEGA 2 VERIFY KAREGA --> BUT COST INCREASE HOGI AND 2 LLM BHI TOH HALOCINATE KAR SHAKTA HAI NA SO FAILS ---> [BUT PAISA HAI SO USR KAR SHAKTE HAI THIK]
//                                 --> ******** APAN FUNCTION/TOOL BANAYENGAI --> 4-5 QUERY LIKHE HONGAI SO AB LLM SE PUCHO KI INMESE KONSA TOOL CHALANA HAI ---> PROBLEM SOLVE APNE HAATH PE CONTROL HAI ------> NEW PROBLEM WITH TOOLS --> KAISE PATA HOGA KITNE TOOLS BANANA HAI --> USER TOH KUCH BHI PUCH SHAKTA HAI NA --> TOH KITNE TOOLS BANAOGAI BATAO --> KUCH BHI QUERIES BAN SHAKTI HAI SO APAN KITNE TOOLS BANAYENGAI ISSUE HAI YE BHI 
//                                          --> **** KYA KARO KI BASCIS QUERIES LIKH DETE HAI APAN THIK ----> AND USER KI BIG QUERIES SMALL SMALL PE BREAK HOKE --> HAMARI SMALL SMALL QUERIES SE SOLVE HONGI AND LAST PE ADD HOKE FINAL SOLUTION DE DENGI --> [BREAK BIG QUERIES IN SMALL --> AND APAN CHOTE CHOTE BASIC TOOLS BANA SHAKTE HAI YE PROBLEM SOLVE DENGAI EASILY BY THESE QUERIES AND AB PROBLEM SOLVE]             
//                                          --> **** SO LLM KO BOLDO AB KI YAHI 5-6 TOOLS LLM KO DO PUCHO YE TOOLS HAI INI MAI SE QUERY SOLVE KARNA HAI TOOL CALLING HOGI BOHOT THIK --> PROBLEM SOLVE   


