// BINARY CLASSIFICATION 

// SEE NOTES EXAMPLE OF BINARY CLASSIFICATION --> SAME KAHANI PEHLE JAISE THIK

// **** DO CORRECTION IF WRONG PREDICT ---> 0.4 [WRONG] AYA SO ---> SO ISKO BHI PUSH KARE JYADA FOR CORRECT ANSWER KE LIYE
//                                     ---> 0.1 [WRONG] AYA S0 **** ISKO UPER WALE SE JYADA PUSH KARNA HOGA FOR CORRECT O/P ---> **** EXPONENTIAL FUNCTION USE KARO FOR JYADA PUSH KARE --> NOT LINEARILY PUSH KARO 
//  --> 0.1 WALE KO JYADA FAST PUSH KARNA HOGA 

// --> SEE BOTH GRAPH 

// --> EXAMPLE --> LET O/P IS 120 --> SO CONVERT IT INTO 0TO1 --> SO 0.6 AYA --> SO LOSS FUNCTION HOGA 1-0.6=0.4 --> SO IMRPOVE 0.4 [CORRECTION HAI YE] **** BOHOT SMALL CORRECTION HAI KYA MAI BOLU LOSS FUNCTION KO KI CORRECTION KARO ITNE CHOTE SE ERROR KA BOHOT SMALL CHANGES AYENGAI YR --> **** AYSA KARNA HAI KI THODA BIG LEVEL PE CORRECTION HOYE [EXPONENTIALLY JYADA CORRECTION HOGA]
// --> **** JO ERROR AYA USKO EXPONENTIALLY DEKHO/BANAO THEN CORRECT KARO EXPONENTIALLY [KYA HAI 120 CONVERT HUA 0.6 PE TOH YE EXPONENTIALLY HO THEN AGAR 0.6 SE 120 PE GAYE TOH WO BHI EXPONENTIALLY JAYE SAMJHE --> SO JO ERROR WAGERA HAI WO BHI APAN EXPONENTIALLY DEKHO]

// --> **** SO WE WANT AYSA GRAPH PEHLE SLOW INC HO THEN FAST INC HO <---- LOG GRAPH 
// --> ACTUAL OUTPUT = 1
// --> -LOG(P) ==> - IS FOR POSITIVE VALUES 
// --> EXAMPLE --> 0.1 HAI SO BOHOT JYADA PUSH CHAIYE AND AGAR 0.9 HAI TOH KAM PUSH CHAIYE --> IF ACTUAL O/P IS 1


// --> SEE EXAMPLE IN PDF --> 
// --> FINAL O/P = 0
// --> PREDICT -->                    0.2    0.4    0.8    0.9
// --> OLD METHOD CORRECTION IS -->  -0.2   -0.4   -0.8    -0.9    [YE METHOD BHI SAHI ANSWER DERA HAI]

// --> SO 0.2 KO SABSE KAM PUSH KARNA HOGA AND 0.9 KO BOHOT JYADA PUCH KARNA HOGA SAMJHE 
// --> LOG(0.9) = -0.2           <
// --> LOG(0.8) = -0.5           < 
// --> LOG(0.4) = -0.7           <-------- SMALL VALUE AARI HAI SO CHNGE FORMULA LITTLE BIT 
// --> LOG(0.2) = -0.8           <
// YAHA JISKO JYADA PUSH CHAIYE USKO KAM PUSH MILRA HAI SO CHANGE HOGA FORMULA THIK 
// METHODS FAILS 

// AS ERROR SABSE JYADA 0.9 PE HAI TOH WEIGHT BHI ISI KA CHANGE HONA CHAIYE NA SABSE JYADA --> SO SABSE BADA ERROR ISI KO DENA CHAIYE NA -->
// FINAL FORMULA ******** ----> SO CHANGE FORMULA [REVERSE THE CONDITION] ----> LOG(1-P)
// --> LOG(1-0.9) = LOG(0.1) = -0.9 
// --> LOG(1-0.8) = LOG(0.7) = -0.7
// --> LOG(1-0.4) = LOG(0.6) = -0.4
// --> LOG(1-0.2) = LOG(0.8) = -0.2 

// ----> ***** SO AB JISKO JYADA PUSH CHAIYE USKO JYADA PUSH MILRA HAI ----> 0.9 KO SABSE JYADA PUSH MILRA HAI AB THIK 




// -->   ACTUAL O/P = 1             |       ACTUAL O/P = 0                               
// -->   -LOG(P)                    |          LOG(1-P)

// -->  EX: 0.8 AND 0.2             |     EX: 0.9 AND 0.4     
// --> -LOG(0.8) -> +0.25                 LOG(1-0.9) -> LOG(0.1) -> -0.91
// --> -LOG(0.2) -> +0.71                 LOG(1-0.4) -> LOG(0.6) -> -0.38 
// --> SO YAHA PE 0.2 KO JYADA      |     -> SO ISME 0.9 KO JYADA PUSH KARNA HOGA SAMJHE  
//     PUSH CHAIYE HAI 



// ---------> FINAL ERROR FORMULA --> -(YLOG(P)-(1-Y)LOG(1-P))
// -> EX: FINAL O/P = 1 AND EXPECTED O/P IS 0.4 --> SO --> -LOG(0.4) --> -LOG(0.4)


// -> ONLINE FORMULA --> LOSS FUNCTION IN BINARY CLASSIFICATION ----> -(YLOG(P)+(1-Y)LOG(1-P))        
// 
// -> ROHIT BHAIYA --> -(YLOG(P)-(1-Y)LOG(1-P))
//       |
//       \/
// W1_NEW = W1_OLD + 0.01 * ERROR * INPUT 


// --> **** ACTUALLY BOTH ARE LIKHNE KA WAY BS CHANGE HAI OK

// --> SEE IN PDF -->        (Y-P) OR ERROR  --> Y-P == ACTUAL - PREDICT 
// --> W1_NEW = W1_OLD + 0.01 * (Y-P) * INPUT 
// OR BY GPT 
// --> W1_NEW = W1_OLD - 0.01 * (P-Y) * INPUT


// --> WE DONT NEED NEW RULES WE WORK WITH ROHIT BHAIYA :-

// --> -(YLOG(P)-(1-Y)LOG(1-P))
// --> W1_NEW = W1_OLD + 0.01 * (Y-P) * INPUT 


// --> AND BY CHATGPT 

// --> -(YLOG(P)+(1-Y)LOG(1-P))
// --> W1_NEW = W1_OLD - N(Y-P) * X
// --> ISME LOG CALCULATE NI KARNA PADEGA BS YAHI EK PROFIT HAI THIK TIME COMPLEXITY ACHI HOGI THODI SI THIK 

