// ----- MOVIE RECOMMENDATION -----

// STEP1 --> IMAGE1 --> 
// STEP2 --> LLM KA WORK 1000 MOVIES DENA --> 1000 OBJECT RETURN KARKE DE IN STRUCTURE FORMAT --> SO WE BUILD GRAPH
//       --> **** YAHA PE YE MISTAKE SHAKTI HAI KI 1000 MOVIE SO 1000 LLM CALL HOGI ---> WORST API LIMIT HIT HO JAYEGI TURANT ----> SO EK KAAM KARO 50-50 KE BATCH BANA KE KARLO 50-50 MOVIE IN 1 BATCH SO TOTAL 20 BATCH THIK HO GYA YE THIK
//       --> **** IF ANY ERROR IN BATCH THEN YE CHOR DEGA US BATCH KO --> SO ISKO OPTIMIZE KARO KI JIS BATCH PE ERROR AYE TOH USKO AGAIN RETRY KAR CHOR NI DE --> **** IF PAID API HAI TOH WE WORK IN PARALLEL UPLOAD PDF IN GEMINI 48 HOURS KE LIYE UPLOAD REHTI HAI --> SO KYA KARO 50-50 KE BATCHES KO PARALLEL PE EXECUTE KARO AND KOI BHI ERROR AYE SO MANAGE KARE USKO CHOR NI DO THIK 
// STEP3 --> GET 1000 MOVIE KA DATA FROM LLM ----> SO INSERT KARA DO IN GRAPHDB (NEO4J) --> WRITE CODE FOR THIS ****CREATE INDEXING FOR EACH FIELD (MOVIES,ACTORS,ETC) SO FAST HO JAYEGI SEARCHING  
//       --> DONT CREATE MULTIPLE NODE FOR 1 USER
//       --> CREATE ACCOUNT IN NEO4J --> DOWNLOAD CREDENTIALS --> AND IT WILL CREATE INSTANCE FOE US 







// -------- PROJECT [CODE PE PARESHAN NI HO --> CHANGES HOTE REHTE HAI] --------

// 1) RUNINDEXING.JS 
// 2) ENTITYEXTRACTOR.JS --> 1000 MOVIES HAI --> 50 MOVIE 1 BATCH --> SO TOTAL BATCHES = 20 --> AND 5-5 (250 EK BAAR MAI) KE BATCHES KO PARALLEL PE CHAIYENGAI --> OR INME 1 MAI 50 HONGAI --> SO 4 HAI MAI PURA WORK HO JAYEGA 





