// 1) **** ADV-TOPIC --> GRAPH-RAG


// --> PROBLEMS WITH RAG SYSTEM :


// -> IMAGE1 -> SUPPOSE 1 PDF HAI AND USME ALL INFO OF USERS HAI -> KI WO KYA BUY KARA HAI AND LOGS HAI[PARTICULAR USER RELATED INFO] AND ALL

// -> 1 QUESTION ASK KI --> ANJALI KO MAI KYA CHIZE RECOMMEND KARU TOP 10 TELL -> RECOMMEND KAREGA YES OR NO -> TELL WITH REASON ?

// -> NORMAL RAG DIVIDE WHOLE PDF IN CHUNKS AND STORE THEM IN VECTORDB THIK --> AND 1 PERSON KA DATA INDIVIDUAL CHUNKS PE DIVIDE HOGA --> YE TOH THIK HAI BUT PDF PE TOH LOGS PRESENT HAI OR YE PUCH RA HAI TOP 10 CHIZE KYA RECOMMEND KARU KAISE BATAYEGA -> YE TOH OUT OF BOUND HUA NA ?  
// -> NORMAL RAG TOH SIMILARITY FIND KAREGA NA KI EX: ANJALI NE SURF LIYA, MICROMAX LIYA, BREAD LIYA SO -> YE ANJALI SE RELATED KUCH CHIZE VECTORDB SE NIKAL KE DEGA BUT --> **** RECOMMENDATION JAISA TOH ISME KUCH HAI HI NI TOH YE RECOMMEND NI KAREGA TOP 10 --> ISME SIRF LOG HAI BS KI YE BUY KIYA YE USER BS
// -> **** VECTOR DB ANSWER NI DE PAYEGA


// --> THINK SOLUTION SELF :

// FIRST -> ANJALI NE AJ TK KYA KYA BUY KIYA HAI
// SECOND -> JO CHIZE ANJALI NE LIYA HAI -> USKO OR KISNE KISNE BUY KIYA HAI 
// THIRD -> AND ANOTHER USER NE OR KYA KYA BUY KIYA HAI WITH THAT PRODUCT

// -> VECTOR DB ANSWER NI DE PAYEGA
// **** --> SO MAI QUESTION KO LLM KO BHEJU GA AND --> QUESTION KO BREAK KARAOGA [LIKE THIS UPER WALA] 
// -> SO MEKO OR BOHOT SARE LOGO KYA KYA KHARIDA SAB PATA LAGGYA BY BREAK SINGLE QUESTION INTO MULTIPLE QUESTIONS 
// -> **** SO KISNE KISNE KYA KHARIDA PATA LAGGYA --> SO USER USER HATA DO AND PRODUCT RECOMMEND KARDO 


// --------------- THIS IS KNOWN AS AGENTIC RAG [BREAK QUESTIONS]----------------

// --> AGENTIC RAG --> TOOL KO BAAR BAAR CALL KARKE WORK KARAO YE THIK

// --> **** BUT HERE IN THIS QUESTION THIS AGENTIC APPROACH FAILS

// -> FAILS WHY --> EX: ANJALI NE 500 PRODUCTS BUY KIYE HAI BUT APAN KO TOP 10 DIKHANE HAI --> TOH BAKI KE 490 TOH GAYE NA  
//               -> SO MAAN LO YE KARE KI TOP 500 PRODUCTS DIKHAYENAI THIK YE SET KAR DIYE PER 
//               -> BUT KOI USER HAI USNE SIRF AJ TK 10 PRODUCT HI BUY KARE HAI TOH BAKI KE -> 490 TOH IRREVALENT HUE NA --> SO YE ATI HAI LIMITATION SAMHE KUCH BHI LIMIT NI SET KAR DENGAI APAN BHI AYSE HI COST LAGTI HAI


// -----------> **** ABHI TK BOTH NORMAL RAG AND AGENTIC RAG DONO FAIL HAI

// -------------------------------------------------------------------------------


// --> IMAGE2 -> ANOTHER EXAMPLE --> PDF HAI : -> CRIME HISTORY OF PEOPES IN INDIA -> KIDNAP ,MURDER AND ALL PRESENT IN PDF WITH THEIR ID[AADHAR CARD]

// -> SUPPOSE 1 PEOPLE NIKHIL 5 SAAL BAAD CHUT RA HAI JAIL SE --> AND POLICE KO 5 AYSE CRIME PATA CHAL JAYE KI NIKHIL KYA KYA KAR SHAKTA HAI --> SO POLICE USPE NAZAR RAKHE 

// -> ASK QUESTION --> KI NIKHIL OR KYA KYA 5 CRIME KAR SHAKTA HAI --> NORMAL RAG ANSWER DE PAYEGA KYA --> SO NORMAL RAG TOH NIKHIL KI HISTORY SE HI --> KUCH KUCH ANSWER DEDEGA JAHA NIKHIL KI BAAT HUI HOGI [SEMENTIC SEARCH] --> **** ACTUAL NOT GIVE CORRECT ANSWER KI IN FUTURE KI 5 KYA CRIME WO KAR SHAKTA HAI 

// -> **** NORMAL RAG FAILS HERE [BECAUSE NORMAL RAG SEMENTIC SEARCH BASED HOTA HAI] --> AND HAMARA QUESTION TOH SEMANTIC SEARCH BASED HAI HI NAHI --> SO FAILS
// -> **** NORMA RAG/RAG --> ONLY DO SEMANTIC SEARCH --> NOT GIVE CORRECT ANSWER 
// -> NORMAL RAG --> QUERY KO LEGA AND SIMILAR ONE FIND IN VECTOR DB AND GIVE RESULT --> ** IF WE ASK LITTLE TWIST QUESTION THEN IT WILL FAILS



// -----------> **** CORRECT ANSWER MILEGA BY : SEE IMAGE3 -> GRAPH BANAKE CONNECT KARKE SABKO --> PREDICT KAR SHAKTE HAI AB NEXT 5 CRIME KYA KAR SHAKTA HAI NIKHIL
//                                                         -> **** NO SEMANTIC MEANING/SEARCH HERE -> BUT WHERE RAG DO SEMENCIC SEARH -> SO FAILS     


// ----------------------------------------------------------------------------------


// -> IMAGE4 -> ANOTHER EXAMPLE -> PDF OF ELON MUSK [BIOGRAPHY] AND HARSHIT/JAGDISH HIS FRIEND --> ELON MUSK KE BARE PE ALL INFO HAI AND HIS FRIENDS INFO TOO --> [ALAG ALAG CHUNK PE DIFF DIFF INFO HAI THIK]

// -> QUESTION : WHO ARE FRIEND OF ELON MUSK AND WHAT THEY DO ?
//  --> SO YE CHUNK KO DEKH KE RATING KAREGA KITNA KYA RELATED HAI --> IMAGE5 --> SO NORMAL RAG FAILS HERE ,
//  --> AGENTIC RAG FAILS ****[FAILS NOT BUT GIVE INCOMPLETE ANSWER] HERE TOO [BREAK QUESTIONS IN MORE SMALL PARTS AND SEARCH INFO FROM VECTORDB][TOP 10 DOST KI INFO LE AYA HOGA AND AGAR 100 DOST HUE TOH 90 CHUT GAYE NA]


//  --------> ********** MEANS BOTH RAG AND AGENTIC RAG WORKS JAHA PE --> EXACT MEANING CHAIYE KISI CHIZ KA ----> BUT **** FAIL JAHA CONNECTION JOD KE ANSWER NIKALNA PADTA HAI 



// --------------------------------------------------------------------------------


// -> IMAGE6 -> ANOTHER EXAMPLE [FAMILY TREE] : -> YE QUESTION SE GPT BHI THINK KARNE LAGA TIME LIYA ANSWER DENE PE --> KON KISKA KYA LAGTA HAI

// QUESTION -> RELATIONSHIP BETWEEN A AND H , A AND B AND ALL --> SO NORMAL RAG ANSWER KAREGA KI NI ?

// --> ******** NORMAL RAG ANSWER NI DE PAYEGA --> RELATIONSHIP NI BATA PAYEGA [INTERRELATE NI KARA PAYEGA] --> NORMAL RAG TOH SIRF A AND H DEKEHE GA KAHA KAHA AYA HAI AND KUCH FALTU RESULT DE DEGA [**** SEMENTIC SEARCH FAIL -> WHERE LITTLE HARD QUESTION WE ASK]

// --> **** RELATIONSHIP EASILY TELL BY ****GRAPHRAG BY MAKING GRAPH -> SEE IMAGE7


// -------------------------------------------------------------------------------


// --> IMAGE8 -> ANOTHER EXAMPLE --> BANKING FILE : YOU HAVE ALREADY PROVIDED ALL THE INFO REGARDING BANKS LOG 
//                                -> PATA HAI LLM COMOANY FRAUD HAI ISME TRANSCATION HUI TOH

// --> QUESTION : IS VEDANT ACCCOUNT IS FRAUD ACCOUNT ? --> TELL BY NORMAL RAG OR NOT --> NORMAL RAG SIRF VEDANT AND FRAUD KO DEKHEGA --> YE DONO DEARCH KAREGA AND KUCH FALTU ANSWER DEDEGA ----> **** BUT LLM COMPANY FRAUD AND VEDANT KE BICH KA RELATION ****NI BATA PAYEGA [NORMAL SEMENTIC SEARCH FAIL HERE]

// --> **** YAHI LIMITATION HAI RELATION NI FIND KAREGA RAG SYSTEM HAMARA --> SIRF SEARCH KAREGA IN VECTORDB

// --> ******** BUT AGAR RELATION DEKHENGAI TOH EASILY ANSWER DE SHAKTE HAI KI --> VEDANT NE PRIYA KO PAISE DIYE PRIYA NE PHONE DEVIE AND PHONE DEVICE NE LLM COMPANY KO BHEJA AND YE FRAUD HAI SO SAB FRAUD HAI --> 
// --> ******** SO GRAPGRAG SE EASILY RELATION BANAKE ANSWER BATA SHAKTE HAI 


// ------------------------------------------------------------------------------


// 2) ----> ******** AGENTICRAG --> IS LIKE RATTU TOTA --> KUCH KUCH BATA DEGA SUPPOSE 10 ME SE 50 ----> BUT JAHA OR DEPTH PE QUESTION ASK --> FAIL AND NOT GIVE FULL ANSWERS 50 PE SE 50


// -----------------------------------------------------------------------------


// 3) ----------GRAPHDB----------

// --> IMAGE9 --> BATANA HAI KI LINKEDIN PE ROHIT KO FRIEND SUGGESTION DENA HAI AND KUCH ROHIT KE FRIENDS HAI ALREADY --> SO ROHIT KE FRIEND KE FRIENDS KO ROHIT KO SUGGEST KARDO

// --> **** EASILY DO BY GRAPHDB -> BY BUILD RELATIONSHIP --> **** BUT NOT DONE BY NORMAL RAG


// --> ******** WHY NOT USE SQL, MONGODB, ETC ? --> WHY USE GRAPHDB ?
// --> **** GraphDB is used because it efficiently handles complex multi-hop relationship traversals natively, whereas SQL and MongoDB require costly joins or application-level logic for the same



